[2025-07-08T11:08:47.809+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-08T11:08:47.818+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-07-08T11:08:45.941067+00:00 [queued]>
[2025-07-08T11:08:47.822+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-07-08T11:08:45.941067+00:00 [queued]>
[2025-07-08T11:08:47.823+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-07-08T11:08:47.830+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_raw_data> on 2025-07-08 11:08:45.941067+00:00
[2025-07-08T11:08:47.834+0000] {standard_task_runner.py:72} INFO - Started process 101 to run task
[2025-07-08T11:08:47.837+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'extract_raw_data', 'manual__2025-07-08T11:08:45.941067+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/driven_data_pipeline.py', '--cfg-path', '/tmp/tmpa560agmc']
[2025-07-08T11:08:47.838+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask extract_raw_data
[2025-07-08T11:08:47.867+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-07-08T11:08:45.941067+00:00 [running]> on host 08d09176ca22
[2025-07-08T11:08:47.903+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='extract_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-08T11:08:45.941067+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-08T11:08:45.941067+00:00'
[2025-07-08T11:08:47.904+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-07-08T11:08:47.905+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-07-08T11:08:47.905+0000] {logging_mixin.py:190} INFO - Current task name:extract_raw_data state:running start_date:2025-07-08 11:08:47.818462+00:00
[2025-07-08T11:08:47.905+0000] {logging_mixin.py:190} INFO - Dag name:extract_raw_data_pipeline and current dag run status:running
[2025-07-08T11:08:47.905+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-08T11:08:47.906+0000] {driven_data_pipeline.py:143} INFO - Started batch processing for 2025-07-08.
[2025-07-08T11:08:47.906+0000] {driven_data_pipeline.py:34} INFO - Created synthetic data for RO country code.
[2025-07-08T11:08:48.015+0000] {driven_data_pipeline.py:100} INFO - Written 538 records to the CSV file.
[2025-07-08T11:08:48.020+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/driven_data_pipeline.py", line 147, in save_raw_data
    _add_id()
  File "/opt/airflow/dags/driven_data_pipeline.py", line 108, in _add_id
    df = pl.read_csv("/opt/airflow/data/raw_data.csv")
  File "/home/airflow/.local/lib/python3.10/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/polars/io/csv/functions.py", line 500, in read_csv
    df = _read_csv_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/polars/io/csv/functions.py", line 646, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
polars.exceptions.ComputeError: could not parse `personal_number` as dtype `i64` at column 'personal_number' (column number 4)

The current offset in the file is 296922 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `personal_number` to the `null_values` list.

Original error: ```remaining bytes non-empty```
[2025-07-08T11:08:48.025+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-07-08T11:08:48.025+0000] {logging_mixin.py:190} INFO - Task start:2025-07-08 11:08:47.818462+00:00 end:2025-07-08 11:08:48.025477+00:00 duration:0.207015
[2025-07-08T11:08:48.025+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_raw_data> dag:<DAG: extract_raw_data_pipeline> dagrun:<DagRun extract_raw_data_pipeline @ 2025-07-08 11:08:45.941067+00:00: manual__2025-07-08T11:08:45.941067+00:00, state:running, queued_at: 2025-07-08 11:08:45.984452+00:00. externally triggered: True>
[2025-07-08T11:08:48.026+0000] {logging_mixin.py:190} INFO - Failure caused by could not parse `personal_number` as dtype `i64` at column 'personal_number' (column number 4)

The current offset in the file is 296922 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `personal_number` to the `null_values` list.

Original error: ```remaining bytes non-empty```
[2025-07-08T11:08:48.026+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_raw_data_pipeline, task_id=extract_raw_data, run_id=manual__2025-07-08T11:08:45.941067+00:00, execution_date=20250708T110845, start_date=20250708T110847, end_date=20250708T110848
[2025-07-08T11:08:48.031+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-08T11:08:48.031+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task extract_raw_data (could not parse `personal_number` as dtype `i64` at column 'personal_number' (column number 4)

The current offset in the file is 296922 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `personal_number` to the `null_values` list.

Original error: ```remaining bytes non-empty```; 101)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/driven_data_pipeline.py", line 147, in save_raw_data
    _add_id()
  File "/opt/airflow/dags/driven_data_pipeline.py", line 108, in _add_id
    df = pl.read_csv("/opt/airflow/data/raw_data.csv")
  File "/home/airflow/.local/lib/python3.10/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/polars/io/csv/functions.py", line 500, in read_csv
    df = _read_csv_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/polars/io/csv/functions.py", line 646, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
polars.exceptions.ComputeError: could not parse `personal_number` as dtype `i64` at column 'personal_number' (column number 4)

The current offset in the file is 296922 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `personal_number` to the `null_values` list.

Original error: ```remaining bytes non-empty```
[2025-07-08T11:08:48.061+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-08T11:08:48.071+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-08T11:08:48.074+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
