[2025-07-08T11:22:09.103+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-08T11:22:09.118+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-07-08T11:22:06.887128+00:00 [queued]>
[2025-07-08T11:22:09.127+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-07-08T11:22:06.887128+00:00 [queued]>
[2025-07-08T11:22:09.127+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-07-08T11:22:09.135+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_raw_data> on 2025-07-08 11:22:06.887128+00:00
[2025-07-08T11:22:09.141+0000] {standard_task_runner.py:72} INFO - Started process 411 to run task
[2025-07-08T11:22:09.150+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'extract_raw_data', 'manual__2025-07-08T11:22:06.887128+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/driven_data_pipeline.py', '--cfg-path', '/tmp/tmpazvedg95']
[2025-07-08T11:22:09.154+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask extract_raw_data
[2025-07-08T11:22:09.251+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-07-08T11:22:06.887128+00:00 [running]> on host 08d09176ca22
[2025-07-08T11:22:09.330+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='extract_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-08T11:22:06.887128+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-08T11:22:06.887128+00:00'
[2025-07-08T11:22:09.339+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-07-08T11:22:09.339+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-07-08T11:22:09.340+0000] {logging_mixin.py:190} INFO - Current task name:extract_raw_data state:running start_date:2025-07-08 11:22:09.120831+00:00
[2025-07-08T11:22:09.340+0000] {logging_mixin.py:190} INFO - Dag name:extract_raw_data_pipeline and current dag run status:running
[2025-07-08T11:22:09.341+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-08T11:22:09.345+0000] {driven_data_pipeline.py:153} INFO - Started batch processing for 2025-07-08.
[2025-07-08T11:22:09.347+0000] {driven_data_pipeline.py:34} INFO - Created synthetic data for RO country code.
[2025-07-08T11:22:09.476+0000] {driven_data_pipeline.py:100} INFO - Written 750 records to the CSV file.
[2025-07-08T11:22:09.476+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/driven_data_pipeline.py", line 157, in save_raw_data
    _add_id()
  File "/opt/airflow/dags/driven_data_pipeline.py", line 120, in _add_id
    uuid_list = [str(uuid.uuid4()) for _ in range(df.height)]
UnboundLocalError: local variable 'df' referenced before assignment
[2025-07-08T11:22:09.481+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-07-08T11:22:09.481+0000] {logging_mixin.py:190} INFO - Task start:2025-07-08 11:22:09.120831+00:00 end:2025-07-08 11:22:09.481553+00:00 duration:0.360722
[2025-07-08T11:22:09.482+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_raw_data> dag:<DAG: extract_raw_data_pipeline> dagrun:<DagRun extract_raw_data_pipeline @ 2025-07-08 11:22:06.887128+00:00: manual__2025-07-08T11:22:06.887128+00:00, state:running, queued_at: 2025-07-08 11:22:06.905971+00:00. externally triggered: True>
[2025-07-08T11:22:09.482+0000] {logging_mixin.py:190} INFO - Failure caused by local variable 'df' referenced before assignment
[2025-07-08T11:22:09.482+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_raw_data_pipeline, task_id=extract_raw_data, run_id=manual__2025-07-08T11:22:06.887128+00:00, execution_date=20250708T112206, start_date=20250708T112209, end_date=20250708T112209
[2025-07-08T11:22:09.486+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-08T11:22:09.487+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 20 for task extract_raw_data (local variable 'df' referenced before assignment; 411)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/driven_data_pipeline.py", line 157, in save_raw_data
    _add_id()
  File "/opt/airflow/dags/driven_data_pipeline.py", line 120, in _add_id
    uuid_list = [str(uuid.uuid4()) for _ in range(df.height)]
UnboundLocalError: local variable 'df' referenced before assignment
[2025-07-08T11:22:09.498+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-08T11:22:09.510+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-08T11:22:09.512+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
