[2025-07-08T11:28:37.361+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-08T11:28:37.367+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.load_raw_data manual__2025-07-08T11:28:33.359043+00:00 [queued]>
[2025-07-08T11:28:37.370+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.load_raw_data manual__2025-07-08T11:28:33.359043+00:00 [queued]>
[2025-07-08T11:28:37.371+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-07-08T11:28:37.376+0000] {taskinstance.py:2888} INFO - Executing <Task(SQLExecuteQueryOperator): load_raw_data> on 2025-07-08 11:28:33.359043+00:00
[2025-07-08T11:28:37.378+0000] {standard_task_runner.py:72} INFO - Started process 541 to run task
[2025-07-08T11:28:37.381+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'load_raw_data', 'manual__2025-07-08T11:28:33.359043+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/driven_data_pipeline.py', '--cfg-path', '/tmp/tmpycylzi_w']
[2025-07-08T11:28:37.381+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask load_raw_data
[2025-07-08T11:28:37.403+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.load_raw_data manual__2025-07-08T11:28:33.359043+00:00 [running]> on host 08d09176ca22
[2025-07-08T11:28:37.438+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='load_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-08T11:28:33.359043+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-08T11:28:33.359043+00:00'
[2025-07-08T11:28:37.439+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-07-08T11:28:37.439+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-07-08T11:28:37.439+0000] {logging_mixin.py:190} INFO - Current task name:load_raw_data state:running start_date:2025-07-08 11:28:37.368026+00:00
[2025-07-08T11:28:37.439+0000] {logging_mixin.py:190} INFO - Dag name:extract_raw_data_pipeline and current dag run status:running
[2025-07-08T11:28:37.439+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-08T11:28:37.440+0000] {sql.py:266} INFO - Executing: 
    COPY driven_raw.raw_batch_data(
    person_name, user_name, email, personal_number, birth_date,
    address, phone, mac_address, ip_address, iban, accessed_at,
    session_duration, download_speed, upload_speed, consumed_traffic, unique_id
    ) 
    FROM '/opt/***/data/raw_data.csv' 
    DELIMITER ',' 
    CSV HEADER;
    
[2025-07-08T11:28:37.443+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-07-08T11:28:37.447+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-07-08T11:28:37.449+0000] {sql.py:509} INFO - Running statement: 
    COPY driven_raw.raw_batch_data(
    person_name, user_name, email, personal_number, birth_date,
    address, phone, mac_address, ip_address, iban, accessed_at,
    session_duration, download_speed, upload_speed, consumed_traffic, unique_id
    ) 
    FROM '/opt/***/data/raw_data.csv' 
    DELIMITER ',' 
    CSV HEADER;
    , parameters: None
[2025-07-08T11:28:37.451+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/opt/***/data/raw_data.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2025-07-08T11:28:37.454+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-07-08T11:28:37.454+0000] {logging_mixin.py:190} INFO - Task start:2025-07-08 11:28:37.368026+00:00 end:2025-07-08 11:28:37.454495+00:00 duration:0.086469
[2025-07-08T11:28:37.454+0000] {logging_mixin.py:190} INFO - Task:<Task(SQLExecuteQueryOperator): load_raw_data> dag:<DAG: extract_raw_data_pipeline> dagrun:<DagRun extract_raw_data_pipeline @ 2025-07-08 11:28:33.359043+00:00: manual__2025-07-08T11:28:33.359043+00:00, state:running, queued_at: 2025-07-08 11:28:33.369829+00:00. externally triggered: True>
[2025-07-08T11:28:37.455+0000] {logging_mixin.py:190} INFO - Failure caused by could not open file "/opt/***/data/raw_data.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
[2025-07-08T11:28:37.455+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_raw_data_pipeline, task_id=load_raw_data, run_id=manual__2025-07-08T11:28:33.359043+00:00, execution_date=20250708T112833, start_date=20250708T112837, end_date=20250708T112837
[2025-07-08T11:28:37.459+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-08T11:28:37.459+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task load_raw_data (could not open file "/opt/***/data/raw_data.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 541)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/opt/***/data/raw_data.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2025-07-08T11:28:37.479+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-08T11:28:37.491+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-08T11:28:37.493+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
